# Generated by Django 5.1.3 on 2025-01-16 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(default='[]')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(default='[]')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=254)),
                ('degree', models.CharField(blank=True, max_length=128)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('profile', models.ManyToManyField(related_name='education', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256)),
                ('linkedin_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True)),
                ('phone_number', models.IntegerField()),
                ('languages', models.TextField(blank=True, default='[]')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.TextField(default='[]')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheivements', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(default='[]')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='workExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place_name', models.CharField(blank=True, max_length=256)),
                ('work_place_job', models.CharField(blank=True, max_length=128)),
                ('work_place_startdate', models.DateField(blank=True)),
                ('work_place_enddate', models.DateField(blank=True)),
                ('work_place', models.CharField(blank=True, max_length=128)),
                ('profile', models.ManyToManyField(related_name='workExperience', to='profiles.profiles')),
            ],
        ),
    ]
