# Generated by Django 5.1.3 on 2025-01-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
