# Generated by Django 5.1.3 on 2025-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profiles_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profilePictures/'),
        ),
    ]
