# Generated by Django 5.1.3 on 2025-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
