# Generated by Django 5.1.3 on 2025-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myposts',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='myposts',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='posts/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='myposts',
            name='resource',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myposts',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
