# Generated by Django 5.1.3 on 2025-02-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addPosts', '0003_alter_myposts_likes_alter_myposts_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myposts',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='myposts',
            name='shares',
        ),
    ]
