# Generated by Django 5.1.3 on 2025-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addPosts', '0004_remove_myposts_likes_remove_myposts_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myposts',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
