# Generated by Django 5.1.3 on 2025-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addPosts', '0005_alter_myposts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myposts',
            name='post',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
