# Generated by Django 5.1.3 on 2025-02-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addPosts', '0006_alter_myposts_post'),
        ('profiles', '0004_profiles_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myposts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myposts', to='profiles.profiles'),
        ),
    ]
