# Generated by Django 5.1.3 on 2025-02-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addPosts', '0007_alter_myposts_profile'),
        ('profiles', '0004_profiles_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('liked_by', models.ManyToManyField(related_name='liked_by', to='profiles.profiles')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='addPosts.myposts')),
            ],
        ),
    ]
