# Generated by Django 5.1.3 on 2024-11-24 09:17

from django.db import migrations, models
#from models import model_names

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ph_no', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        
    ]
