# Generated by Django 5.1.3 on 2025-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
