# Generated by Django 5.1.3 on 2025-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
